### ISSUE TITLE
M66 win10 64bit: 

### ISSUE THREAD

**Issue by m-alperensener** [Wiz-IO/platform-opencpu#1]
I am getting this error even after installing platform as guided, using git.
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\malpe\\Documents\\PlatformIO\\Projects\\denemeM66\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Could not find a version that satisfies the requirement '>=4.8.3' for your system 'windows_amd64'"

**Comment by Wiz-IO** [comment]
platform-opencpu/README.md
Тhe platform will migrate here **platform-quectel** for all Quectel modules
This GIT is old and I will delete....

Install this 
https://github.com/Wiz-IO/platform-quectel

**Comment by m-alperensener** [comment]
Problem solved thanks

Georgi Angelov <notifications@github.com>, 10 May 2019 Cum, 18:18 tarihinde
şunu yazdı:

**Comment by Wiz-IO** [comment]
You welcome...
