### ISSUE TITLE
Is it possible to assign priority to tasks?

### ISSUE THREAD

**Issue by ASL07** [Wiz-IO/platform-opencpu#3]
Hi,

Does OpenCPU allow to assign priority to user defined tasks?
I am registering my tasks i custom_task_cfg.h but all of them end up having the same priority value (4)

Thanks

**Comment by Wiz-IO** [comment]
BC66? ... is not implemented

**Comment by ASL07** [comment]
Yes, BC66
Thanks @Wiz-IO

**Comment by Wiz-IO** [comment]
if you want to experiment:

/* only for BC66NBR01A10 & SDK v1.5*/
void ( * vTaskPrioritySet)(void * xTask, int uxNewPriority ) = (void ( * )( void * , int)) 0x08074745; 

void * handle = Ql_OS_GetCurrentTaskHandle();
vTaskPrioritySet(handle, 5);

:)

**Comment by ASL07** [comment]
Ql_OS_GetCurrentTaskHandle is undefined for this platform
What SDK version is used for framework-quectel bc66?

Are we sure that vTaskPrioritySet() will allways be located at 0x08074745 ?

**Comment by Wiz-IO** [comment]
Ql_OS_GetCurrentTaskHandle() exist in OpenCPU v1.5
address is **only** for firmware BC66NBR01A10

**Comment by ASL07** [comment]
Ok, I won't try implement the solution you proposed then, I want my code to work regardless of FW version.

Anyway, this is the error I am getting with the latest opencpu framework:
```
Processing bc66 (platform: quectel; board: bc66; framework: opencpu)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
<<<<<<<<<<<< QUECTEL BC66 MODULE 2018 Georgi Angelov >>>>>>>>>>>>
CONFIGURATION: https://docs.platformio.org/page/boards/quectel/bc66.html
PLATFORM: Quectel 2.0.14 #5dbec3f > Quectel BC66 module
HARDWARE: ARM, MT2625 78MHz, 97.66KB RAM, 195.31KB Flash
DEBUG: Current (uart) On-board (uart)
PACKAGES: 
 - framework-quectel b91f56c 
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio/build/bc66/src/tasks/get_temperature_task.o
Linking .pio/build/bc66/program.elf
.pio/build/bc66/src/tasks/get_temperature_task.o: In function `get_temperature_task':
/Users/developer/Code/opencpu/pioproject/src/tasks/get_temperature_task.c:77: undefined reference to `Ql_OS_GetCurrentTaskHandle'
```

**Comment by Wiz-IO** [comment]
![Untitled](https://user-images.githubusercontent.com/14574834/76323919-0131c980-62ee-11ea-98cd-3872c4802e9c.png)

**Comment by Wiz-IO** [comment]
update :)
https://github.com/Wiz-IO/platform-quectel/wiki/SDK-BC66

**Comment by ASL07** [comment]
Great! 
Is it fixed in the new version?
I will give it a try

**Comment by ASL07** [comment]
> if you want to experiment:
> 
> /* only for BC66NBR01A10 & SDK v1.5*/
> void ( * vTaskPrioritySet)(void * xTask, int uxNewPriority ) = (void ( * )( void * , int)) 0x08074745;
> 
> void * handle = Ql_OS_GetCurrentTaskHandle();
> vTaskPrioritySet(handle, 5);
> 
> :)

I have tested this with BC66NBR01A10 & SDK v1.5 version and it works

**Comment by Wiz-IO** [comment]
:) this call is valid only for this firmware
